### ISSUE TITLE
Allow manual input of creation time of WAV files?

### ISSUE THREAD

**Issue by ymtoo** [org-arl/AcousticAnnotations.jl#1]
`dts` of WAV files is based on `ctime(f)` to get the changed time (https://github.com/JuliaLang/julia/pull/39731). Changed time could be different from creation time. It would be more flexible if the creation time can be added as an input argument, e.g.,

```julia
dt = DateTime("2019-09-11T13:02:08") # creation time
Base.push!(adb::ADB, filename, device, location, dt)

# By default, it falls back to the original implementation
Base.push!(adb::ADB, filename, device, location)
```

**Comment by mchitre** [comment]
Yes, was thinking about how to deal with creation/modification time across systems. This seems like a good option. Will implement as a keyword parameter shortly.

API:
```
dt = DateTime("2019-09-11T13:02:08") # creation time
Base.push!(adb::ADB, filename, device, location; dts=dt)
```

**Comment by mchitre** [comment]
Done.
